version: "3.6"

services:
 db:
    container_name: ${POSTGRES_HOST}
    image: postgres:latest
    volumes:
      - db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - ${POSTGRES_PORT}

 web:
    build:
      context: .
      dockerfile: _prod/Dockerfile
    command: uvicorn ${served_fastapi}.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - ${NGINX_EXPOSE}:8000
    depends_on:
      - db

volumes:
  db: