version: "3.6"

services:
 db:
    container_name: ${APPLICATION_NAME}_postgres
    image: postgres:latest
    volumes:
      - db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - ${POSTGRES_PORT}

 web:
    container_name: ${APPLICATION_NAME}_web
    build:
      context: .
      dockerfile: _prod/Dockerfile
    command: uvicorn ${APPLICATION_NAME}.main:app --host 0.0.0.0 --port 8000 --workers ${WASGI_WORKERS}
    volumes:
      - .:/code
      - _static:/code/_static
    expose:
      - 8000
    depends_on:
      - db

 nginx:
   container_name: ${APPLICATION_NAME}_nginx
   build: _prod/nginx
   ports:
     - ${NGINX_EXPOSE}:80
   depends_on:
     - web
   volumes:
     - _static:/code/_static


volumes:
  db:
  _static:
