version: "3.6"

services:
  db:
    container_name: ${APPLICATION_NAME}_postgres
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - ${POSTGRES_PORT}

  web:
    container_name: ${APPLICATION_NAME}_web
    build:
      context: .
      dockerfile: _prod/Dockerfile
    command: uvicorn application.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  pgadmin:
    container_name: ${APPLICATION_NAME}_pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db


volumes:
  db:
